FROM rust:1.92-trixie

RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install diesel_cli --no-default-features --features postgres

WORKDIR /app

COPY backend/migrations ./migrations
COPY backend/diesel.toml ./diesel.toml

RUN mkdir -p src

CMD ["diesel", "database", "reset"]
