name: Astro CI (mise)
on:
  push:
    branches:
      - main
    paths: &astro_paths
      - frontend/**
  pull_request:
    paths: *astro_paths
jobs:
  astro_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup mise
        uses: jdx/mise-action@v3
      - name: Run Astro CI
        run: mise ci-astro
